apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm # Name of the Kustomization resource
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./helm/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
